In [2]:
import pandas as pd

In [3]:
df_fin_sup=pd.read_csv(f'funds/StateUT-wise Approved Financial Support to the Teachers (Elementary and Secondary Schools) under Samagra Shiksha during 2021-22.csv')

In [6]:
df_fin_sup=df_fin_sup.drop('Sl. No.', axis=1)

In [7]:
df_fin_sup

                                  State/UT   Approved
0              Andaman and Nicobar Islands     1478.9
1                           Andhra Pradesh    49240.2
2                        Arunachal Pradesh    15128.5
3                                    Assam    65690.4
4                                    Bihar   360438.5
5                               Chandigarh     6561.2
6                             Chattishgarh     7552.6
7                                    Delhi     5197.9
8   Daman and Diu - Dadar and Nagar Haveli     3045.0
9                                      Goa      329.9
10                                 Gujarat    74898.3
11                                 Haryana    40249.1
12                        Himachal Pradesh    10650.0
13                       Jammu and Kashmir    46160.9
14                               Jharkhand    87891.0
15                               Karnataka    32806.2
16                                  Kerala     1789.7
17                                  Ladakh        0.0
18                             Lakshadweep       78.6
19                          Madhya Pradesh   198144.2
20                             Maharashtra     8580.6
21                                 Manipur     8850.8
22                               Meghalaya    27691.2
23                                 Mizoram     7383.7
24                                Nagaland    10179.1
25                                  Odisha   132758.0
26                              Puducherry        0.0
27                                  Punjab    26719.8
28                               Rajasthan   213643.8
29                                  Sikkim     1461.6
30                              Tamil Nadu   117821.5
31                               Telangana    39473.1
32                                 Tripura    10866.0
33                           Uttar Pradesh   401060.9
34                             Uttarakhand    12700.5
35                             West Bengal   123169.6
36                                   Total  2149691.3